/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryexampletp2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Driver;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyanp
 */
public class BmwForm extends javax.swing.JFrame {

    /**
     * Creates new form BmwForm
     */
    public BmwForm() {
        initComponents();
    }
    Connection con1;
    PreparedStatement pst;

    private void table_update() {
        try {
            int x;

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
                pst = con1.prepareStatement("select * from `java_bmw` ");
                ResultSet rs = pst.executeQuery();

                ResultSetMetaData rsd = rs.getMetaData();
                x = rsd.getColumnCount();

                DefaultTableModel d = (DefaultTableModel) BmwTable.getModel();
                d.setRowCount(0);

                while (rs.next()) {

                    Vector v2 = new Vector();
                    for (int i = 1; i <= x; i++) {
                        v2.add(rs.getString("id_bmw"));
                        v2.add(rs.getString("make"));
                        v2.add(rs.getString("model"));
                        v2.add(rs.getString("price"));
                        v2.add(rs.getString("year"));
                        v2.add(rs.getString("fueltype"));
                        v2.add(rs.getString("color"));
                        v2.add(rs.getString("breakhorsepower"));
                        v2.add(rs.getString("drivetype"));
                        v2.add(rs.getString("quantity"));
                        v2.add(rs.getString("mileage"));

                    }

                    d.addRow(v2);

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        MakeTextBox1 = new javax.swing.JTextField();
        ProductsAddButton1 = new javax.swing.JButton();
        DriveTypeComboBox = new javax.swing.JComboBox<>();
        ProductRemoveButton = new javax.swing.JButton();
        ProductUpdateButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ColourTextBox = new javax.swing.JTextField();
        ModelTextBox = new javax.swing.JTextField();
        YearTextBox = new javax.swing.JTextField();
        FuelTypeTextBox = new javax.swing.JTextField();
        PowerTextBox = new javax.swing.JTextField();
        QuantityTextBox = new javax.swing.JTextField();
        MileageTextBox = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        PrintButton = new javax.swing.JButton();
        PriceTextBox = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        YearWarningLabel = new javax.swing.JLabel();
        PriceWarningLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        MainFormOrdersLabel = new javax.swing.JLabel();
        AudiLabel = new javax.swing.JLabel();
        MainFormStockLevels = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MainFormCustomerLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        MainFormStockLevels1 = new javax.swing.JLabel();
        MainFormStockLevels2 = new javax.swing.JLabel();
        MainFormStockLevels3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BmwTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(102, 0, 0));
        jLabel16.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(191, 30, 46));
        jLabel16.setText("Make");

        jLabel17.setBackground(new java.awt.Color(102, 0, 0));
        jLabel17.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(191, 30, 46));
        jLabel17.setText("Model");

        MakeTextBox1.setBackground(new java.awt.Color(255, 255, 255));
        MakeTextBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ProductsAddButton1.setBackground(new java.awt.Color(255, 255, 255));
        ProductsAddButton1.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        ProductsAddButton1.setForeground(new java.awt.Color(191, 30, 46));
        ProductsAddButton1.setText("Submit");
        ProductsAddButton1.setToolTipText("");
        ProductsAddButton1.setActionCommand("");
        ProductsAddButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductsAddButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsAddButton1ActionPerformed(evt);
            }
        });

        DriveTypeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        DriveTypeComboBox.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        DriveTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatic" }));
        DriveTypeComboBox.setBorder(new javax.swing.border.MatteBorder(null));
        DriveTypeComboBox.setMinimumSize(new java.awt.Dimension(64, 26));

        ProductRemoveButton.setBackground(new java.awt.Color(255, 255, 255));
        ProductRemoveButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        ProductRemoveButton.setForeground(new java.awt.Color(191, 30, 46));
        ProductRemoveButton.setText("Remove");
        ProductRemoveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductRemoveButtonActionPerformed(evt);
            }
        });

        ProductUpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        ProductUpdateButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        ProductUpdateButton.setForeground(new java.awt.Color(191, 30, 46));
        ProductUpdateButton.setText("Update");
        ProductUpdateButton.setActionCommand("");
        ProductUpdateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductUpdateButtonActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(102, 0, 0));
        jLabel18.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(191, 30, 46));
        jLabel18.setText("Fuel Type");

        jLabel19.setBackground(new java.awt.Color(102, 0, 0));
        jLabel19.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(191, 30, 46));
        jLabel19.setText("Year");

        jLabel20.setBackground(new java.awt.Color(102, 0, 0));
        jLabel20.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(191, 30, 46));
        jLabel20.setText("Quantity");

        jLabel21.setBackground(new java.awt.Color(102, 0, 0));
        jLabel21.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(191, 30, 46));
        jLabel21.setText("Drive Type");

        jLabel22.setBackground(new java.awt.Color(102, 0, 0));
        jLabel22.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(191, 30, 46));
        jLabel22.setText("Colour");

        jLabel23.setBackground(new java.awt.Color(102, 0, 0));
        jLabel23.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(191, 30, 46));
        jLabel23.setText("BHP");

        ColourTextBox.setBackground(new java.awt.Color(255, 255, 255));
        ColourTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ModelTextBox.setBackground(new java.awt.Color(255, 255, 255));
        ModelTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ModelTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ModelTextBoxKeyPressed(evt);
            }
        });

        YearTextBox.setBackground(new java.awt.Color(255, 255, 255));
        YearTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        YearTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                YearTextBoxKeyPressed(evt);
            }
        });

        FuelTypeTextBox.setBackground(new java.awt.Color(255, 255, 255));
        FuelTypeTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        PowerTextBox.setBackground(new java.awt.Color(255, 255, 255));
        PowerTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PowerTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerTextBoxActionPerformed(evt);
            }
        });
        PowerTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PowerTextBoxKeyPressed(evt);
            }
        });

        QuantityTextBox.setBackground(new java.awt.Color(255, 255, 255));
        QuantityTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        QuantityTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTextBoxActionPerformed(evt);
            }
        });
        QuantityTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QuantityTextBoxKeyPressed(evt);
            }
        });

        MileageTextBox.setBackground(new java.awt.Color(255, 255, 255));
        MileageTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MileageTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MileageTextBoxActionPerformed(evt);
            }
        });
        MileageTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MileageTextBoxKeyPressed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(102, 0, 0));
        jLabel24.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(191, 30, 46));
        jLabel24.setText("Mileage");

        PrintButton.setBackground(new java.awt.Color(255, 255, 255));
        PrintButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        PrintButton.setForeground(new java.awt.Color(191, 30, 46));
        PrintButton.setText("Print");
        PrintButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PrintButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintButtonMouseClicked(evt);
            }
        });
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });

        PriceTextBox.setBackground(new java.awt.Color(255, 255, 255));
        PriceTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PriceTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PriceTextBoxKeyPressed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(102, 0, 0));
        jLabel25.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(191, 30, 46));
        jLabel25.setText("Price");

        jPanel5.setBackground(new java.awt.Color(191, 30, 46));
        jPanel5.setMaximumSize(new java.awt.Dimension(164, 782));
        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(164, 782));

        jLabel12.setBackground(new java.awt.Color(102, 0, 0));
        jLabel12.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dashboard");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        MainFormOrdersLabel.setBackground(new java.awt.Color(102, 0, 0));
        MainFormOrdersLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormOrdersLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainFormOrdersLabel.setText("Orders");
        MainFormOrdersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormOrdersLabelMouseClicked(evt);
            }
        });

        AudiLabel.setBackground(new java.awt.Color(102, 0, 0));
        AudiLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        AudiLabel.setForeground(new java.awt.Color(255, 255, 255));
        AudiLabel.setText("Audi");
        AudiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AudiLabelMouseClicked(evt);
            }
        });

        MainFormStockLevels.setBackground(new java.awt.Color(102, 0, 0));
        MainFormStockLevels.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormStockLevels.setForeground(new java.awt.Color(255, 255, 255));
        MainFormStockLevels.setText("Bmw");
        MainFormStockLevels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormStockLevelsMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Log Out");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        MainFormCustomerLabel.setBackground(new java.awt.Color(102, 0, 0));
        MainFormCustomerLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormCustomerLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainFormCustomerLabel.setText("Customers");
        MainFormCustomerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormCustomerLabelMouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(102, 0, 0));
        jLabel13.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Exit");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        MainFormStockLevels1.setBackground(new java.awt.Color(102, 0, 0));
        MainFormStockLevels1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormStockLevels1.setForeground(new java.awt.Color(255, 255, 255));
        MainFormStockLevels1.setText("Toyota");
        MainFormStockLevels1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormStockLevels1MouseClicked(evt);
            }
        });

        MainFormStockLevels2.setBackground(new java.awt.Color(102, 0, 0));
        MainFormStockLevels2.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormStockLevels2.setForeground(new java.awt.Color(255, 255, 255));
        MainFormStockLevels2.setText("Volkswagen");
        MainFormStockLevels2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormStockLevels2MouseClicked(evt);
            }
        });

        MainFormStockLevels3.setBackground(new java.awt.Color(102, 0, 0));
        MainFormStockLevels3.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormStockLevels3.setForeground(new java.awt.Color(255, 255, 255));
        MainFormStockLevels3.setText("Mercedes");
        MainFormStockLevels3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormStockLevels3MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BmwDatabase");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainFormCustomerLabel)
                    .addComponent(MainFormOrdersLabel)
                    .addComponent(AudiLabel)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3)
                    .addComponent(MainFormStockLevels1)
                    .addComponent(MainFormStockLevels2)
                    .addComponent(MainFormStockLevels3)
                    .addComponent(MainFormStockLevels))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(64, 64, 64)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormOrdersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AudiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormStockLevels1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormStockLevels2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainFormStockLevels3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainFormStockLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        BmwTable.setBackground(new java.awt.Color(255, 255, 255));
        BmwTable.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        BmwTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_bmw", "Make", "Model", "Price", "Year", "Fuel Type", "Colour", "BHP", "Transmission", "Quantity", "Mileage"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BmwTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BmwTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BmwTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel25)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel22)))
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21)
                                .addComponent(jLabel18))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ModelTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MakeTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(YearTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ColourTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FuelTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PowerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(QuantityTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DriveTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MileageTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ProductsAddButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ProductUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ProductRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(YearWarningLabel)
                    .addComponent(PriceWarningLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(PriceWarningLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 595, Short.MAX_VALUE)
                .addComponent(YearWarningLabel)
                .addGap(58, 58, 58))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MakeTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModelTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColourTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FuelTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriveTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MileageTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductsAddButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ProductsAddButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsAddButton1ActionPerformed

        String make = MakeTextBox1.getText();
        String model = ModelTextBox.getText();
        String price = PriceTextBox.getText();
        String year = YearTextBox.getText();
        String colour = ColourTextBox.getText();
        String fuelType = FuelTypeTextBox.getText();
        String power = PowerTextBox.getText();
        String quantity = QuantityTextBox.getText();
        String driveType = DriveTypeComboBox.getSelectedItem().toString();
        String mileage = MileageTextBox.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
            pst = con1.prepareStatement("insert into `bmw` (make, model, price, year, fueltype, color, breakhorsepower ,drivetype, quantity, mileage) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            pst.setString(1, make);
            pst.setString(2, model);
            pst.setString(3, price);
            pst.setString(4, year);
            pst.setString(5, fuelType);
            pst.setString(6, colour);
            pst.setString(7, power);
            pst.setString(8, driveType);
            pst.setString(9, quantity);
            pst.setString(10, mileage);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Car Model has been added to the database!!!");
            table_update();
            //setting all values to null after insertion
            MakeTextBox1.setText("");
            ModelTextBox.setText("");
            PriceTextBox.setText("");
            YearTextBox.setText("");
            ColourTextBox.setText("");
            FuelTypeTextBox.setText("");
            PowerTextBox.setText("");
            QuantityTextBox.setText("");
            MileageTextBox.setText("");

            DriveTypeComboBox.setSelectedIndex(0);
            MakeTextBox1.requestFocus();
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        } finally {
            try {
                if (pst != null) {
                    pst.close();
                }
                if (con1 != null) {
                    con1.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_ProductsAddButton1ActionPerformed

    private void ProductRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductRemoveButtonActionPerformed
        // TODO add your handling code here:
        //Remove button

        DefaultTableModel d1 = (DefaultTableModel) BmwTable.getModel();
        int selectIndex = BmwTable.getSelectedRow();

        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

        int warningPopup = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?", "WARNING", JOptionPane.YES_NO_CANCEL_OPTION);

        if (warningPopup == JOptionPane.YES_OPTION) {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");

                con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
                pst = con1.prepareStatement("delete from `java_bmw` where id_bmw = ? ");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record has been deleted!!!");
                table_update();
                ModelTextBox.setText("");
                MakeTextBox1.setText("");
                PriceTextBox.setText("");
                YearTextBox.setText("");
                ColourTextBox.setText("");
                FuelTypeTextBox.setText("");
                PowerTextBox.setText("");
                QuantityTextBox.setText("");
                MileageTextBox.setText("");

                DriveTypeComboBox.setSelectedIndex(0);
                MakeTextBox1.requestFocus();
                ModelTextBox.requestFocus();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ProductRemoveButtonActionPerformed

    private void ProductUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductUpdateButtonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel d1 = (DefaultTableModel) BmwTable.getModel();
        int selectIndex = BmwTable.getSelectedRow();
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

        String make = MakeTextBox1.getText();
        String model = ModelTextBox.getText();
        String price = PriceTextBox.getText();
        String year = YearTextBox.getText();
        String colour = ColourTextBox.getText();
        String FuelType = FuelTypeTextBox.getText();
        String Power = PowerTextBox.getText();
        String Quantity = QuantityTextBox.getText();
        String DriveType = DriveTypeComboBox.getSelectedItem().toString();
        String Mileage = MileageTextBox.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
            pst = con1.prepareStatement("update `java_bmw` set make = ?, model = ?, price = ?, year = ?, fueltype = ?, color = ?, breakhorsepower = ?, drivetype = ?, "
                    + "quantity = ?, mileage = ? where id_bmw = ? ");
            pst.setString(1, make);
            pst.setString(2, model);
            pst.setString(3, price);
            pst.setString(4, year);
            pst.setString(5, FuelType);
            pst.setString(6, colour);
            pst.setString(7, Power);
            pst.setString(8, DriveType);
            pst.setString(9, Quantity);
            pst.setString(10, Mileage);
            pst.setInt(11, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Database has been Updated!!!");
            table_update();
            //sets values to null after update
            ModelTextBox.setText("");
            MakeTextBox1.setText("");
            PriceTextBox.setText("");
            YearTextBox.setText("");
            ColourTextBox.setText("");
            FuelTypeTextBox.setText("");
            PowerTextBox.setText("");
            QuantityTextBox.setText("");
            DriveTypeComboBox.setSelectedIndex(1);
            MileageTextBox.setText("");

            MakeTextBox1.requestFocus();;

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProductUpdateButtonActionPerformed

    private void ModelTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModelTextBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelTextBoxKeyPressed

    private void YearTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YearTextBoxKeyPressed
        // TODO add your handling code here:
        //Key Pressed Validation for numbers only
    }//GEN-LAST:event_YearTextBoxKeyPressed

    private void PowerTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerTextBoxActionPerformed

    private void PowerTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PowerTextBoxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerTextBoxKeyPressed

    private void QuantityTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTextBoxActionPerformed

    private void QuantityTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityTextBoxKeyPressed
        // TODO add your handling code here:
        //Key Pressed Validation for numbers only
    }//GEN-LAST:event_QuantityTextBoxKeyPressed

    private void MileageTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MileageTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MileageTextBoxActionPerformed

    private void MileageTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MileageTextBoxKeyPressed
        // TODO add your handling code here:
        //Key Pressed Validation for numbers only
    }//GEN-LAST:event_MileageTextBoxKeyPressed

    private void PrintButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintButtonMouseClicked
        // TODO add your handling code here:
        //Print button fucntion

        int warningPopup = JOptionPane.showConfirmDialog(null, "Set ORIENTATION to LANDSCAPE and MARGINS to 1.0, 0.0, 1.0, 0.0", "WARNING!!!", JOptionPane.YES_NO_OPTION);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String headerField = "Printed on " + sdf.format(new Date());

        MessageFormat header = new MessageFormat(headerField);
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");

        if (warningPopup == JOptionPane.YES_OPTION) {

            try {

                BmwTable.print(JTable.PrintMode.NORMAL, header, footer);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_PrintButtonMouseClicked

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void PriceTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PriceTextBoxKeyPressed
        // TODO add your handling code here:
        //Key Pressed Validation for numbers only
    }//GEN-LAST:event_PriceTextBoxKeyPressed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        MainForm MainForm = new MainForm();
        MainForm.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void AudiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudiLabelMouseClicked
        // TODO add your handling code here:

        AudiForm AudiForm = new AudiForm();
        AudiForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_AudiLabelMouseClicked

    private void MainFormStockLevelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormStockLevelsMouseClicked
        // TODO add your handling code here:
        BmwForm BmwForm = new BmwForm();
        BmwForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormStockLevelsMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        LoginForm AdminLoginForm = new LoginForm();
        AdminLoginForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void MainFormCustomerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormCustomerLabelMouseClicked
        // TODO add your handling code here:
        CustomerForm MyCustomerForm = new CustomerForm();
        MyCustomerForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormCustomerLabelMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void MainFormStockLevels1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormStockLevels1MouseClicked
        // TODO add your handling code here:
        ToyotaForm ToyotaForm = new ToyotaForm();
        ToyotaForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormStockLevels1MouseClicked

    private void MainFormStockLevels2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormStockLevels2MouseClicked
        // TODO add your handling code here:
        VolkswagenForm VolkswagenForm = new VolkswagenForm();
        VolkswagenForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormStockLevels2MouseClicked

    private void MainFormStockLevels3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormStockLevels3MouseClicked
        // TODO add your handling code here:
        MercedesForm MercedesForm = new MercedesForm();
        MercedesForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormStockLevels3MouseClicked

    private void BmwTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BmwTableMouseClicked
        // TODO add your handling code here:

        DefaultTableModel d1 = (DefaultTableModel) BmwTable.getModel();
        int selectIndex = BmwTable.getSelectedRow();

        MakeTextBox1.setText(d1.getValueAt(selectIndex, 1).toString());
        ModelTextBox.setText(d1.getValueAt(selectIndex, 2).toString());
        PriceTextBox.setText(d1.getValueAt(selectIndex, 3).toString());
        YearTextBox.setText(d1.getValueAt(selectIndex, 4).toString());
        FuelTypeTextBox.setText(d1.getValueAt(selectIndex, 5).toString());
        ColourTextBox.setText(d1.getValueAt(selectIndex, 6).toString());
        PowerTextBox.setText(d1.getValueAt(selectIndex, 7).toString());
        DriveTypeComboBox.setSelectedItem(d1.getValueAt(selectIndex, 8).toString());
        QuantityTextBox.setText(d1.getValueAt(selectIndex, 9).toString());
        MileageTextBox.setText(d1.getValueAt(selectIndex, 10).toString());
    }//GEN-LAST:event_BmwTableMouseClicked

    private void MainFormOrdersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormOrdersLabelMouseClicked
        // TODO add your handling code here:
        OrdersForm OrdersForm = new OrdersForm();
        OrdersForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormOrdersLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BmwForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BmwForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BmwForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BmwForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BmwForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AudiLabel;
    private javax.swing.JTable BmwTable;
    private javax.swing.JTextField ColourTextBox;
    private javax.swing.JComboBox<String> DriveTypeComboBox;
    private javax.swing.JTextField FuelTypeTextBox;
    private javax.swing.JLabel MainFormCustomerLabel;
    private javax.swing.JLabel MainFormOrdersLabel;
    private javax.swing.JLabel MainFormStockLevels;
    private javax.swing.JLabel MainFormStockLevels1;
    private javax.swing.JLabel MainFormStockLevels2;
    private javax.swing.JLabel MainFormStockLevels3;
    private javax.swing.JTextField MakeTextBox1;
    private javax.swing.JTextField MileageTextBox;
    private javax.swing.JTextField ModelTextBox;
    private javax.swing.JTextField PowerTextBox;
    private javax.swing.JTextField PriceTextBox;
    private javax.swing.JLabel PriceWarningLabel;
    private javax.swing.JButton PrintButton;
    private javax.swing.JButton ProductRemoveButton;
    private javax.swing.JButton ProductUpdateButton;
    private javax.swing.JButton ProductsAddButton1;
    private javax.swing.JTextField QuantityTextBox;
    private javax.swing.JTextField YearTextBox;
    private javax.swing.JLabel YearWarningLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
