/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryexampletp2;

/**
 *
 * @author Pantelis Xiourouppas
 */
public class AdminOrEmployeeForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminOrEmployeeForm
     */
    public AdminOrEmployeeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmployeeLoginButton = new javax.swing.JButton();
        CreateEmployeeButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        AdminLoginButton1 = new javax.swing.JButton();
        CreateAdminButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(191, 30, 46));

        jLabel1.setBackground(new java.awt.Color(191, 30, 46));
        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ASTON AUTOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        EmployeeLoginButton.setBackground(new java.awt.Color(255, 255, 255));
        EmployeeLoginButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        EmployeeLoginButton.setForeground(new java.awt.Color(191, 30, 46));
        EmployeeLoginButton.setText("Employee Login");
        EmployeeLoginButton.setBorder(new javax.swing.border.MatteBorder(null));
        EmployeeLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeLoginButtonMouseClicked(evt);
            }
        });

        CreateEmployeeButton.setBackground(new java.awt.Color(255, 255, 255));
        CreateEmployeeButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        CreateEmployeeButton.setForeground(new java.awt.Color(191, 30, 46));
        CreateEmployeeButton.setText("Create Employee Account");
        CreateEmployeeButton.setToolTipText("");
        CreateEmployeeButton.setBorder(new javax.swing.border.MatteBorder(null));
        CreateEmployeeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateEmployeeButtonMouseClicked(evt);
            }
        });
        CreateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateEmployeeButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(255, 255, 255));
        ExitButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(191, 30, 46));
        ExitButton.setText("Exit");
        ExitButton.setBorder(new javax.swing.border.MatteBorder(null));
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        AdminLoginButton1.setBackground(new java.awt.Color(255, 255, 255));
        AdminLoginButton1.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        AdminLoginButton1.setForeground(new java.awt.Color(191, 30, 46));
        AdminLoginButton1.setText("Admin Login");
        AdminLoginButton1.setBorder(new javax.swing.border.MatteBorder(null));
        AdminLoginButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLoginButton1MouseClicked(evt);
            }
        });
        AdminLoginButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginButton1ActionPerformed(evt);
            }
        });

        CreateAdminButton1.setBackground(new java.awt.Color(255, 255, 255));
        CreateAdminButton1.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        CreateAdminButton1.setForeground(new java.awt.Color(191, 30, 46));
        CreateAdminButton1.setText("Create Admin Account");
        CreateAdminButton1.setToolTipText("");
        CreateAdminButton1.setBorder(new javax.swing.border.MatteBorder(null));
        CreateAdminButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateAdminButton1MouseClicked(evt);
            }
        });
        CreateAdminButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAdminButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CreateAdminButton1)
                            .addComponent(AdminLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CreateEmployeeButton)
                            .addComponent(EmployeeLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 141, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AdminLoginButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateAdminButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(153, 153, 153)))
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeLoginButtonMouseClicked
        EmployeeLoginForm EmployeeLogin = new EmployeeLoginForm();
        EmployeeLogin.setVisible(true);

        dispose();


    }//GEN-LAST:event_EmployeeLoginButtonMouseClicked

    private void CreateEmployeeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateEmployeeButtonMouseClicked

        AddEmployeeForm AddEmployee = new AddEmployeeForm();
        AddEmployee.setVisible(true);


    }//GEN-LAST:event_CreateEmployeeButtonMouseClicked

    private void CreateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEmployeeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateEmployeeButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void AdminLoginButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLoginButton1MouseClicked
        // TODO add your handling code here:
        LoginForm AdminLogin = new LoginForm();
        AdminLogin.setVisible(true);

        setVisible(false);
    }//GEN-LAST:event_AdminLoginButton1MouseClicked

    private void AdminLoginButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLoginButton1ActionPerformed

    private void CreateAdminButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAdminButton1MouseClicked
        // TODO add your handling code here:
        AddAdminForm AddAdminForm = new AddAdminForm();
        AddAdminForm.setVisible(true);

    }//GEN-LAST:event_CreateAdminButton1MouseClicked

    private void CreateAdminButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAdminButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAdminButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminOrEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminOrEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminOrEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminOrEmployeeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminOrEmployeeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLoginButton1;
    private javax.swing.JButton CreateAdminButton1;
    private javax.swing.JButton CreateEmployeeButton;
    private javax.swing.JButton EmployeeLoginButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
