/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryexampletp2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Driver;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyanp
 */
public class CustomerForm extends javax.swing.JFrame {

    /**
     * Creates new form CustomerForm
     */
    public CustomerForm() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CustomerExitLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        CustomerFormAddButton = new javax.swing.JButton();
        CustomerDeleteButton = new javax.swing.JButton();
        UpdateCustomerTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(191, 30, 46));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Customer Database");

        jLabel12.setBackground(new java.awt.Color(102, 0, 0));
        jLabel12.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Admin");

        jLabel6.setBackground(new java.awt.Color(102, 0, 0));
        jLabel6.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Orders");

        jLabel4.setBackground(new java.awt.Color(102, 0, 0));
        jLabel4.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Products");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(102, 0, 0));
        jLabel10.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Stock Levels");

        jLabel3.setBackground(new java.awt.Color(102, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Log Out");

        jLabel11.setBackground(new java.awt.Color(102, 0, 0));
        jLabel11.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Customers");

        CustomerExitLabel.setBackground(new java.awt.Color(102, 0, 0));
        CustomerExitLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        CustomerExitLabel.setForeground(new java.awt.Color(255, 255, 255));
        CustomerExitLabel.setText("Exit");
        CustomerExitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerExitLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(CustomerExitLabel)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addGap(115, 115, 115)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomerExitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        CustomerTable.setBackground(new java.awt.Color(255, 255, 255));
        CustomerTable.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Email", "Password", "Phone", "Address", "Postcode"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        CustomerFormAddButton.setBackground(new java.awt.Color(255, 255, 255));
        CustomerFormAddButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        CustomerFormAddButton.setForeground(new java.awt.Color(191, 30, 46));
        CustomerFormAddButton.setText("Add Customer");
        CustomerFormAddButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CustomerFormAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerFormAddButtonMouseClicked(evt);
            }
        });
        CustomerFormAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerFormAddButtonActionPerformed(evt);
            }
        });

        CustomerDeleteButton.setBackground(new java.awt.Color(255, 255, 255));
        CustomerDeleteButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        CustomerDeleteButton.setForeground(new java.awt.Color(191, 30, 46));
        CustomerDeleteButton.setText("Delete");
        CustomerDeleteButton.setToolTipText("");
        CustomerDeleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CustomerDeleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerDeleteButtonMouseClicked(evt);
            }
        });
        CustomerDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerDeleteButtonActionPerformed(evt);
            }
        });

        UpdateCustomerTable.setBackground(new java.awt.Color(255, 255, 255));
        UpdateCustomerTable.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        UpdateCustomerTable.setForeground(new java.awt.Color(191, 30, 46));
        UpdateCustomerTable.setText("Update Table");
        UpdateCustomerTable.setToolTipText("");
        UpdateCustomerTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateCustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateCustomerTableMouseClicked(evt);
            }
        });
        UpdateCustomerTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCustomerTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdateCustomerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerFormAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(CustomerDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(CustomerFormAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateCustomerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustomerDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //database connect fucntion
    public Connection getConnected() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {

            System.out.println(ex.getMessage());

        }

        Connection connect = null;

        try {
            connect = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
        } catch (SQLException ex) {

            System.out.println(ex.getMessage());

        }

        return connect;
    }
    Connection con1;
    PreparedStatement pst;

    private void table_update() {
        try {
            int x;

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
                pst = con1.prepareStatement("SELECT * FROM `customers`");
                ResultSet rs = pst.executeQuery();

                ResultSetMetaData rsd = rs.getMetaData();
                x = rsd.getColumnCount();

                DefaultTableModel d = (DefaultTableModel) CustomerTable.getModel();
                d.setRowCount(0);

                while (rs.next()) {

                    Vector v2 = new Vector();
                    for (int i = 1; i <= x; i++) {
                        v2.add(rs.getInt("id"));
                        v2.add(rs.getString("name"));
                        v2.add(rs.getString("email"));
                        v2.add(rs.getString("password"));
                        v2.add(rs.getString("phone"));
                        v2.add(rs.getString("address"));
                        v2.add(rs.getString("postcode"));

                    }
                    d.addRow(v2);

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        CarDatabaseForm MyProductsForm = new CarDatabaseForm();
        MyProductsForm.setVisible(true);

        setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void CustomerExitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerExitLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CustomerExitLabelMouseClicked

    private void CustomerFormAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerFormAddButtonMouseClicked


    }//GEN-LAST:event_CustomerFormAddButtonMouseClicked

    private void CustomerFormAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerFormAddButtonActionPerformed
        // TODO add your handling code here:
        AddCustomerForm MyAddUserForm = new AddCustomerForm();
        MyAddUserForm.setVisible(true);

    }//GEN-LAST:event_CustomerFormAddButtonActionPerformed

    private void CustomerDeleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerDeleteButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerDeleteButtonMouseClicked

    private void CustomerDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerDeleteButtonActionPerformed
        // TODO add your handling code here:

        //Remove button
        DefaultTableModel d1 = (DefaultTableModel) CustomerTable.getModel();
        int selectIndex = CustomerTable.getSelectedRow();

        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

        int warningPopup = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?", "WARNING", JOptionPane.YES_NO_CANCEL_OPTION);

        if (warningPopup == JOptionPane.YES_OPTION) {

            try {
                Class.forName("com.mysql.jdbc.Driver");

                con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
                pst = con1.prepareStatement("DELETE FROM `customers` where id = ? ");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record has been deleted!!!");
                table_update();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_CustomerDeleteButtonActionPerformed

    private void UpdateCustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateCustomerTableMouseClicked
        // TODO add your handling code here:
        Connection con = getConnected();
        Statement statement;
        DefaultTableModel model = (DefaultTableModel) CustomerTable.getModel();

        try {

            statement = con.createStatement();

            for (int i = 0; i < model.getRowCount(); i++) {

                int id = Integer.valueOf(model.getValueAt(i, 0).toString());
                String name = model.getValueAt(i, 1).toString();
                String email = model.getValueAt(i, 2).toString();
                String password = model.getValueAt(i, 3).toString();
                String phone = model.getValueAt(i, 4).toString();
                String address = model.getValueAt(i, 5).toString();
                String postcode = model.getValueAt(i, 6).toString();
                String updateQuery = "UPDATE `customers` SET `name`='" + name + "',`email`='" + email + "',`password`='" + password + "',`phone`='" + phone + "',`address`='" + address + "',`postcode`='" + postcode + "' WHERE `id` = " + id;

                statement.addBatch(updateQuery);

            }

            int[] updateRow = statement.executeBatch();
            System.out.println(updateRow.length);

            JOptionPane.showMessageDialog(null, "Database has been Updated!!!");
            table_update();

        } catch (SQLException ex) {
            Logger.getLogger(CustomerForm.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_UpdateCustomerTableMouseClicked

    private void UpdateCustomerTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCustomerTableActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_UpdateCustomerTableActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        // TODO add your handling code here:

        //EditCustomerForm EditForm = new EditCustomerForm();
        //EditForm.setVisible(true);

    }//GEN-LAST:event_CustomerTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CustomerDeleteButton;
    private javax.swing.JLabel CustomerExitLabel;
    private javax.swing.JButton CustomerFormAddButton;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JButton UpdateCustomerTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
