/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventoryexampletp2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Driver;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cyanp
 */
public class OrdersForm extends javax.swing.JFrame {

    /**
     * Creates new form OrdersForm
     */
    public OrdersForm() {
        initComponents();
        table_update();
        ItemUpdate();
    }
    Connection con1;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        YearWarningLabel = new javax.swing.JLabel();
        PriceWarningLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        MainFormOrdersLabel = new javax.swing.JLabel();
        AudiLabel = new javax.swing.JLabel();
        MainFormStockLevels = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MainFormCustomerLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        MainFormStockLevels1 = new javax.swing.JLabel();
        MainFormStockLevels2 = new javax.swing.JLabel();
        MainFormStockLevels3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(191, 30, 46));
        jPanel5.setMaximumSize(new java.awt.Dimension(164, 782));
        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(164, 782));

        jLabel12.setBackground(new java.awt.Color(102, 0, 0));
        jLabel12.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dashboard");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        MainFormOrdersLabel.setBackground(new java.awt.Color(102, 0, 0));
        MainFormOrdersLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormOrdersLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainFormOrdersLabel.setText("Orders");
        MainFormOrdersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormOrdersLabelMouseClicked(evt);
            }
        });

        AudiLabel.setBackground(new java.awt.Color(102, 0, 0));
        AudiLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        AudiLabel.setForeground(new java.awt.Color(255, 255, 255));
        AudiLabel.setText("Audi");
        AudiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AudiLabelMouseClicked(evt);
            }
        });

        MainFormStockLevels.setBackground(new java.awt.Color(102, 0, 0));
        MainFormStockLevels.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormStockLevels.setForeground(new java.awt.Color(255, 255, 255));
        MainFormStockLevels.setText("Bmw");
        MainFormStockLevels.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormStockLevelsMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 0, 0));
        jLabel3.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Log Out");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        MainFormCustomerLabel.setBackground(new java.awt.Color(102, 0, 0));
        MainFormCustomerLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormCustomerLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainFormCustomerLabel.setText("Customers");
        MainFormCustomerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormCustomerLabelMouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(102, 0, 0));
        jLabel13.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Exit");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        MainFormStockLevels1.setBackground(new java.awt.Color(102, 0, 0));
        MainFormStockLevels1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormStockLevels1.setForeground(new java.awt.Color(255, 255, 255));
        MainFormStockLevels1.setText("Toyota");
        MainFormStockLevels1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormStockLevels1MouseClicked(evt);
            }
        });

        MainFormStockLevels2.setBackground(new java.awt.Color(102, 0, 0));
        MainFormStockLevels2.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormStockLevels2.setForeground(new java.awt.Color(255, 255, 255));
        MainFormStockLevels2.setText("Volkswagen");
        MainFormStockLevels2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormStockLevels2MouseClicked(evt);
            }
        });

        MainFormStockLevels3.setBackground(new java.awt.Color(102, 0, 0));
        MainFormStockLevels3.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        MainFormStockLevels3.setForeground(new java.awt.Color(255, 255, 255));
        MainFormStockLevels3.setText("Mercedes");
        MainFormStockLevels3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainFormStockLevels3MouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Orders Database");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainFormCustomerLabel)
                    .addComponent(MainFormOrdersLabel)
                    .addComponent(AudiLabel)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3)
                    .addComponent(MainFormStockLevels1)
                    .addComponent(MainFormStockLevels2)
                    .addComponent(MainFormStockLevels3)
                    .addComponent(MainFormStockLevels))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(64, 64, 64)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormOrdersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AudiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormStockLevels1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormStockLevels2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainFormStockLevels3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainFormStockLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFormCustomerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        OrderTable.setBackground(new java.awt.Color(255, 255, 255));
        OrderTable.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderId", "CustomerId", "Name", "Email", "Address", "Postcode", "PaymentMethod", "OrderTime", "TotalCost", "OrderStatus"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrderTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OrderTable);
        if (OrderTable.getColumnModel().getColumnCount() > 0) {
            OrderTable.getColumnModel().getColumn(5).setHeaderValue("Postcode");
            OrderTable.getColumnModel().getColumn(6).setHeaderValue("PaymentMethod");
            OrderTable.getColumnModel().getColumn(7).setHeaderValue("OrderTime");
            OrderTable.getColumnModel().getColumn(8).setHeaderValue("TotalCost");
            OrderTable.getColumnModel().getColumn(9).setHeaderValue("OrderStatus");
        }

        ItemTable.setBackground(new java.awt.Color(255, 255, 255));
        ItemTable.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderItemId", "OrderId", "Make", "Model", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ItemTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItemTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ItemTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(YearWarningLabel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PriceWarningLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(PriceWarningLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(YearWarningLabel)
                .addGap(58, 58, 58))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void OrderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrderTableMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_OrderTableMouseClicked
    private void table_update() {
        try {
            int x;

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
                pst = con1.prepareStatement("select * from `orders` ");
                ResultSet rs = pst.executeQuery();

                ResultSetMetaData rsd = rs.getMetaData();
                x = rsd.getColumnCount();

                DefaultTableModel d = (DefaultTableModel) OrderTable.getModel();
                d.setRowCount(0);

                while (rs.next()) {

                    Vector v2 = new Vector();
                    for (int i = 1; i <= x; i++) {
                        v2.add(rs.getString("OrderId"));
                        v2.add(rs.getString("CustomerId"));
                        v2.add(rs.getString("Name"));
                        v2.add(rs.getString("Email"));
                        v2.add(rs.getString("Address"));
                        v2.add(rs.getString("Postcode"));
                        v2.add(rs.getString("PaymentMethod"));
                        v2.add(rs.getString("OrderTime"));
                        v2.add(rs.getString("TotalCost"));
                        v2.add(rs.getString("OrderStatus"));

                    }

                    d.addRow(v2);

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void ItemUpdate() {
        try {
            int x;

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
                pst = con1.prepareStatement("select * from `orderitems` ");
                ResultSet rs = pst.executeQuery();

                ResultSetMetaData rsd = rs.getMetaData();
                x = rsd.getColumnCount();

                DefaultTableModel d = (DefaultTableModel) ItemTable.getModel();
                d.setRowCount(0);

                while (rs.next()) {

                    Vector v2 = new Vector();
                    for (int i = 1; i <= x; i++) {
                        v2.add(rs.getString("OrderItemId"));
                        v2.add(rs.getString("OrderId"));
                        v2.add(rs.getString("Make"));
                        v2.add(rs.getString("Model"));
                        v2.add(rs.getString("Quantity"));
                        v2.add(rs.getString("Price"));

                    }

                    d.addRow(v2);

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(BmwForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void MainFormStockLevels3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormStockLevels3MouseClicked
        // TODO add your handling code here:
        MercedesForm MercedesForm = new MercedesForm();
        MercedesForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormStockLevels3MouseClicked

    private void MainFormStockLevels2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormStockLevels2MouseClicked
        // TODO add your handling code here:
        VolkswagenForm VolkswagenForm = new VolkswagenForm();
        VolkswagenForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormStockLevels2MouseClicked

    private void MainFormStockLevels1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormStockLevels1MouseClicked
        // TODO add your handling code here:
        ToyotaForm ToyotaForm = new ToyotaForm();
        ToyotaForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormStockLevels1MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void MainFormCustomerLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormCustomerLabelMouseClicked
        // TODO add your handling code here:
        CustomerForm MyCustomerForm = new CustomerForm();
        MyCustomerForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormCustomerLabelMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        LoginForm AdminLoginForm = new LoginForm();
        AdminLoginForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void MainFormStockLevelsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormStockLevelsMouseClicked
        // TODO add your handling code here:
        BmwForm BmwForm = new BmwForm();
        BmwForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_MainFormStockLevelsMouseClicked

    private void AudiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AudiLabelMouseClicked
        // TODO add your handling code here:

        AudiForm AudiForm = new AudiForm();
        AudiForm.setVisible(true);

        dispose();
    }//GEN-LAST:event_AudiLabelMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        MainForm MainForm = new MainForm();
        MainForm.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void ItemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItemTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemTableMouseClicked

    private void MainFormOrdersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainFormOrdersLabelMouseClicked
        // TODO add your handling code here:
        OrdersForm OrdersForm = new OrdersForm();
        OrdersForm.setVisible(true);
    }//GEN-LAST:event_MainFormOrdersLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AudiLabel;
    private javax.swing.JTable ItemTable;
    private javax.swing.JLabel MainFormCustomerLabel;
    private javax.swing.JLabel MainFormOrdersLabel;
    private javax.swing.JLabel MainFormStockLevels;
    private javax.swing.JLabel MainFormStockLevels1;
    private javax.swing.JLabel MainFormStockLevels2;
    private javax.swing.JLabel MainFormStockLevels3;
    private javax.swing.JTable OrderTable;
    private javax.swing.JLabel PriceWarningLabel;
    private javax.swing.JLabel YearWarningLabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
