package inventoryexampletp2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Driver;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pantelis Xiourouppas
 */
public class ToyotaForm extends javax.swing.JFrame {

    /**
     * Creates new form ProductsForm
     */
    public ToyotaForm() {
        //loads data from function!!
        initComponents();
        table_update();
    }

    Connection con1;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        AdminLabel = new javax.swing.JLabel();
        OrdersLabel = new javax.swing.JLabel();
        ProductsLabel = new javax.swing.JLabel();
        StockLabel = new javax.swing.JLabel();
        LogOutLabel = new javax.swing.JLabel();
        CustomersLabel = new javax.swing.JLabel();
        ProductsFormExitLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        MakeTextBox = new javax.swing.JTextField();
        ProductsAddButton = new javax.swing.JButton();
        DriveTypeComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarTable = new javax.swing.JTable();
        ProductRemoveButton = new javax.swing.JButton();
        ProductUpdateButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ColourTextBox = new javax.swing.JTextField();
        ModelTextBox = new javax.swing.JTextField();
        YearTextBox = new javax.swing.JTextField();
        FuelTypeTextBox = new javax.swing.JTextField();
        PowerTextBox = new javax.swing.JTextField();
        QuantityTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MileageTextBox = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ConditionTextBox = new javax.swing.JTextField();
        PrintButton = new javax.swing.JButton();
        PriceTextBox = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        YearWarningLabel = new javax.swing.JLabel();
        PriceWarningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(191, 30, 46));

        AdminLabel.setBackground(new java.awt.Color(102, 0, 0));
        AdminLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminLabel.setText("Admin");
        AdminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLabelMouseClicked(evt);
            }
        });

        OrdersLabel.setBackground(new java.awt.Color(102, 0, 0));
        OrdersLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        OrdersLabel.setForeground(new java.awt.Color(255, 255, 255));
        OrdersLabel.setText("Orders");

        ProductsLabel.setBackground(new java.awt.Color(102, 0, 0));
        ProductsLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        ProductsLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProductsLabel.setText("Products");

        StockLabel.setBackground(new java.awt.Color(102, 0, 0));
        StockLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        StockLabel.setForeground(new java.awt.Color(255, 255, 255));
        StockLabel.setText("Stock Levels");

        LogOutLabel.setBackground(new java.awt.Color(102, 0, 0));
        LogOutLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        LogOutLabel.setForeground(new java.awt.Color(255, 255, 255));
        LogOutLabel.setText("Log Out");

        CustomersLabel.setBackground(new java.awt.Color(102, 0, 0));
        CustomersLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        CustomersLabel.setForeground(new java.awt.Color(255, 255, 255));
        CustomersLabel.setText("Customers");
        CustomersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomersLabelMouseClicked(evt);
            }
        });

        ProductsFormExitLabel.setBackground(new java.awt.Color(102, 0, 0));
        ProductsFormExitLabel.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        ProductsFormExitLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProductsFormExitLabel.setText("Exit");
        ProductsFormExitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsFormExitLabelMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Toyota Database");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductsFormExitLabel)
                            .addComponent(LogOutLabel)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CustomersLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(StockLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ProductsLabel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AdminLabel)
                            .addComponent(OrdersLabel)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(AdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OrdersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addComponent(LogOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductsFormExitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jLabel14.setBackground(new java.awt.Color(102, 0, 0));
        jLabel14.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(191, 30, 46));
        jLabel14.setText("Make");

        jLabel15.setBackground(new java.awt.Color(102, 0, 0));
        jLabel15.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(191, 30, 46));
        jLabel15.setText("Model");

        MakeTextBox.setBackground(new java.awt.Color(255, 255, 255));
        MakeTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ProductsAddButton.setBackground(new java.awt.Color(255, 255, 255));
        ProductsAddButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        ProductsAddButton.setForeground(new java.awt.Color(191, 30, 46));
        ProductsAddButton.setText("Submit");
        ProductsAddButton.setToolTipText("");
        ProductsAddButton.setActionCommand("");
        ProductsAddButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductsAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsAddButtonActionPerformed(evt);
            }
        });

        DriveTypeComboBox.setBackground(new java.awt.Color(255, 255, 255));
        DriveTypeComboBox.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        DriveTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatic" }));
        DriveTypeComboBox.setBorder(new javax.swing.border.MatteBorder(null));
        DriveTypeComboBox.setMinimumSize(new java.awt.Dimension(64, 26));

        CarTable.setBackground(new java.awt.Color(255, 255, 255));
        CarTable.setFont(new java.awt.Font("Sitka Heading", 0, 14)); // NOI18N
        CarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Make", "Model", "Price [£]", "Year", "Fuel Type", "Colour", "Horse Power", "Drive Type", "Quantity", "Mileage", "Condition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CarTable);
        if (CarTable.getColumnModel().getColumnCount() > 0) {
            CarTable.getColumnModel().getColumn(0).setResizable(false);
            CarTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        ProductRemoveButton.setBackground(new java.awt.Color(255, 255, 255));
        ProductRemoveButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        ProductRemoveButton.setForeground(new java.awt.Color(191, 30, 46));
        ProductRemoveButton.setText("Remove");
        ProductRemoveButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductRemoveButtonActionPerformed(evt);
            }
        });

        ProductUpdateButton.setBackground(new java.awt.Color(255, 255, 255));
        ProductUpdateButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        ProductUpdateButton.setForeground(new java.awt.Color(191, 30, 46));
        ProductUpdateButton.setText("Update");
        ProductUpdateButton.setActionCommand("");
        ProductUpdateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProductUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductUpdateButtonActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(102, 0, 0));
        jLabel16.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(191, 30, 46));
        jLabel16.setText("Fuel Type");

        jLabel17.setBackground(new java.awt.Color(102, 0, 0));
        jLabel17.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(191, 30, 46));
        jLabel17.setText("Year");

        jLabel18.setBackground(new java.awt.Color(102, 0, 0));
        jLabel18.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(191, 30, 46));
        jLabel18.setText("Quantity");

        jLabel19.setBackground(new java.awt.Color(102, 0, 0));
        jLabel19.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(191, 30, 46));
        jLabel19.setText("Drive Type");

        jLabel20.setBackground(new java.awt.Color(102, 0, 0));
        jLabel20.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(191, 30, 46));
        jLabel20.setText("Colour");

        jLabel21.setBackground(new java.awt.Color(102, 0, 0));
        jLabel21.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(191, 30, 46));
        jLabel21.setText("BHP");

        ColourTextBox.setBackground(new java.awt.Color(255, 255, 255));
        ColourTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ModelTextBox.setBackground(new java.awt.Color(255, 255, 255));
        ModelTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        YearTextBox.setBackground(new java.awt.Color(255, 255, 255));
        YearTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        YearTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                YearTextBoxKeyPressed(evt);
            }
        });

        FuelTypeTextBox.setBackground(new java.awt.Color(255, 255, 255));
        FuelTypeTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        PowerTextBox.setBackground(new java.awt.Color(255, 255, 255));
        PowerTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PowerTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerTextBoxActionPerformed(evt);
            }
        });
        PowerTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PowerTextBoxKeyPressed(evt);
            }
        });

        QuantityTextBox.setBackground(new java.awt.Color(255, 255, 255));
        QuantityTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        QuantityTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityTextBoxActionPerformed(evt);
            }
        });
        QuantityTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                QuantityTextBoxKeyPressed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(191, 30, 46));
        jLabel5.setText("Toyota Inventory System");

        MileageTextBox.setBackground(new java.awt.Color(255, 255, 255));
        MileageTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MileageTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MileageTextBoxActionPerformed(evt);
            }
        });
        MileageTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MileageTextBoxKeyPressed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(102, 0, 0));
        jLabel22.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(191, 30, 46));
        jLabel22.setText("Mileage");

        jLabel23.setBackground(new java.awt.Color(102, 0, 0));
        jLabel23.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(191, 30, 46));
        jLabel23.setText("Condition");

        ConditionTextBox.setBackground(new java.awt.Color(255, 255, 255));
        ConditionTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConditionTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConditionTextBoxActionPerformed(evt);
            }
        });

        PrintButton.setBackground(new java.awt.Color(255, 255, 255));
        PrintButton.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        PrintButton.setForeground(new java.awt.Color(191, 30, 46));
        PrintButton.setText("Print");
        PrintButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PrintButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintButtonMouseClicked(evt);
            }
        });
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });

        PriceTextBox.setBackground(new java.awt.Color(255, 255, 255));
        PriceTextBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PriceTextBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PriceTextBoxKeyPressed(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(102, 0, 0));
        jLabel24.setFont(new java.awt.Font("Sitka Heading", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(191, 30, 46));
        jLabel24.setText("Price");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(MakeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(30, 30, 30))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel24)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ModelTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(PriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel17)
                                            .addGap(40, 40, 40)
                                            .addComponent(YearTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel21)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PowerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(QuantityTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel20))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ColourTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FuelTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addGap(18, 18, 18)
                                            .addComponent(DriveTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel22)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MileageTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(ConditionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ProductsAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ProductUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addComponent(ProductRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(YearWarningLabel)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(PriceWarningLabel)
                                .addGap(112, 112, 112)))))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MakeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ModelTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PriceWarningLabel)
                        .addGap(18, 18, 18)
                        .addComponent(PriceTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YearWarningLabel)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YearTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColourTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FuelTypeTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriveTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MileageTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConditionTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductsAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void table_update() {
        try {
            int x;

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
                pst = con1.prepareStatement("select * from `toyota` ");
                ResultSet rs = pst.executeQuery();

                ResultSetMetaData rsd = rs.getMetaData();
                x = rsd.getColumnCount();

                DefaultTableModel d = (DefaultTableModel) CarTable.getModel();
                d.setRowCount(0);

                while (rs.next()) {

                    Vector v2 = new Vector();
                    for (int i = 1; i <= x; i++) {
                        v2.add(rs.getString("id"));
                        v2.add(rs.getString("make"));
                        v2.add(rs.getString("model"));
                        v2.add(rs.getString("price"));
                        v2.add(rs.getString("year"));
                        v2.add(rs.getString("fueltype"));
                        v2.add(rs.getString("color"));
                        v2.add(rs.getString("breakhorsepower"));
                        v2.add(rs.getString("drivetype"));
                        v2.add(rs.getString("quantity"));
                        v2.add(rs.getString("mileage"));
                        v2.add(rs.getString("conditionofcar"));

                    }

                    d.addRow(v2);

                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void ProductsAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsAddButtonActionPerformed

        String make = MakeTextBox.getText();
        String model = ModelTextBox.getText();
        double price = Double.parseDouble(PriceTextBox.getText());
        int year = Integer.parseInt(YearTextBox.getText());
        String colour = ColourTextBox.getText();
        String fuelType = FuelTypeTextBox.getText();
        int power = Integer.parseInt(PowerTextBox.getText());
        int quantity = Integer.parseInt(QuantityTextBox.getText());
        String driveType = DriveTypeComboBox.getSelectedItem().toString();
        int mileage = Integer.parseInt(MileageTextBox.getText());
        String condition = ConditionTextBox.getText();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
            pst = con1.prepareStatement("insert into `toyota` (make, model, price, year, fueltype, color, breakhorsepower, "
                    + "drivetype, quantity, mileage, conditionofcar) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
            pst.setString(1, make);
            pst.setString(2, model);
            pst.setDouble(3, price);
            pst.setInt(4, year);
            pst.setString(5, fuelType);
            pst.setString(6, colour);
            pst.setInt(7, power);
            pst.setString(8, driveType);
            pst.setInt(9, quantity);
            pst.setInt(10, mileage);
            pst.setString(11, condition);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Car Model has been added to the database!!!");
            table_update();
            //setting all values to null after insertion
            MakeTextBox.setText("");
            ModelTextBox.setText("");
            PriceTextBox.setText("");
            YearTextBox.setText("");
            ColourTextBox.setText("");
            FuelTypeTextBox.setText("");
            PowerTextBox.setText("");
            QuantityTextBox.setText("");
            MileageTextBox.setText("");
            ConditionTextBox.setText("");
            DriveTypeComboBox.setSelectedIndex(0);
            MakeTextBox.requestFocus();
        } catch (SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        } finally {
            try {
                if (pst != null) {
                    pst.close();
                }
                if (con1 != null) {
                    con1.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }


    }//GEN-LAST:event_ProductsAddButtonActionPerformed

    private void ProductUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductUpdateButtonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel d1 = (DefaultTableModel) CarTable.getModel();
        int selectIndex = CarTable.getSelectedRow();
        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

        String make = MakeTextBox.getText();
        String model = ModelTextBox.getText();
        String price = PriceTextBox.getText();
        String year = YearTextBox.getText();
        String colour = ColourTextBox.getText();
        String FuelType = FuelTypeTextBox.getText();
        String Power = PowerTextBox.getText();
        String Quantity = QuantityTextBox.getText();
        String DriveType = DriveTypeComboBox.getSelectedItem().toString();
        String Mileage = MileageTextBox.getText();
        String Condition = ConditionTextBox.getText();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
            pst = con1.prepareStatement("update `toyota` set make = ?, model = ?, price = ?, year = ?, fueltype = ?, color = ?, breakhorsepower = ?, drivetype = ?, "
                    + "quantity = ?, mileage = ?, conditionofcar = ? where id = ? ");
            pst.setString(1, make);
            pst.setString(2, model);
            pst.setString(3, price);
            pst.setString(4, year);
            pst.setString(5, FuelType);
            pst.setString(6, colour);
            pst.setString(7, Power);
            pst.setString(8, DriveType);
            pst.setString(9, Quantity);
            pst.setString(10, Mileage);
            pst.setString(11, Condition);
            pst.setInt(12, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Database has been Updated!!!");
            table_update();
            //sets values to null after update
            ModelTextBox.setText("");
            MakeTextBox.setText("");
            PriceTextBox.setText("");
            YearTextBox.setText("");
            ColourTextBox.setText("");
            FuelTypeTextBox.setText("");
            PowerTextBox.setText("");
            QuantityTextBox.setText("");
            DriveTypeComboBox.setSelectedIndex(1);
            MileageTextBox.setText("");
            ConditionTextBox.setText("");
            MakeTextBox.requestFocus();;

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ProductUpdateButtonActionPerformed

    private void CarTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarTableMouseClicked
        // TODO add your handling code here:

        DefaultTableModel d1 = (DefaultTableModel) CarTable.getModel();
        int selectIndex = CarTable.getSelectedRow();

        MakeTextBox.setText(d1.getValueAt(selectIndex, 1).toString());
        ModelTextBox.setText(d1.getValueAt(selectIndex, 2).toString());
        PriceTextBox.setText(d1.getValueAt(selectIndex, 3).toString());
        YearTextBox.setText(d1.getValueAt(selectIndex, 4).toString());
        FuelTypeTextBox.setText(d1.getValueAt(selectIndex, 5).toString());
        ColourTextBox.setText(d1.getValueAt(selectIndex, 6).toString());
        PowerTextBox.setText(d1.getValueAt(selectIndex, 7).toString());
        DriveTypeComboBox.setSelectedItem(d1.getValueAt(selectIndex, 8).toString());
        QuantityTextBox.setText(d1.getValueAt(selectIndex, 9).toString());
        MileageTextBox.setText(d1.getValueAt(selectIndex, 10).toString());
        ConditionTextBox.setText(d1.getValueAt(selectIndex, 11).toString());


    }//GEN-LAST:event_CarTableMouseClicked

    private void ProductRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductRemoveButtonActionPerformed
        // TODO add your handling code here:
        //Remove button

        DefaultTableModel d1 = (DefaultTableModel) CarTable.getModel();
        int selectIndex = CarTable.getSelectedRow();

        int id = Integer.parseInt(d1.getValueAt(selectIndex, 0).toString());

        int warningPopup = JOptionPane.showConfirmDialog(null, "Do you want to delete this record?", "WARNING", JOptionPane.YES_NO_CANCEL_OPTION);

        if (warningPopup == JOptionPane.YES_OPTION) {

            try {
                Class.forName("com.mysql.jdbc.Driver");

                con1 = DriverManager.getConnection("jdbc:mysql://localhost/inventory", "root", "");
                pst = con1.prepareStatement("delete from `toyota` where id = ? ");
                pst.setInt(1, id);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record has been deleted!!!");
                table_update();
                ModelTextBox.setText("");
                MakeTextBox.setText("");
                PriceTextBox.setText("");
                YearTextBox.setText("");
                ColourTextBox.setText("");
                FuelTypeTextBox.setText("");
                PowerTextBox.setText("");
                QuantityTextBox.setText("");
                MileageTextBox.setText("");
                ConditionTextBox.setText("");

                DriveTypeComboBox.setSelectedIndex(0);
                MakeTextBox.requestFocus();
                ModelTextBox.requestFocus();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ToyotaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_ProductRemoveButtonActionPerformed

    private void AdminLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLabelMouseClicked

    private void ProductsFormExitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsFormExitLabelMouseClicked
        // TODO add your handling code here:

        //this.dispose();
        System.exit(0);
    }//GEN-LAST:event_ProductsFormExitLabelMouseClicked

    private void PowerTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerTextBoxActionPerformed

    private void QuantityTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityTextBoxActionPerformed

    private void CustomersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersLabelMouseClicked
        // TODO add your handling code here:

        CustomerForm MyCustomerForm = new CustomerForm();
        MyCustomerForm.setVisible(true);

        setVisible(false);
    }//GEN-LAST:event_CustomersLabelMouseClicked

    private void MileageTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MileageTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MileageTextBoxActionPerformed

    private void ConditionTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConditionTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConditionTextBoxActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void PrintButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintButtonMouseClicked
        // TODO add your handling code here:
        //Print button fucntion

        int warningPopup = JOptionPane.showConfirmDialog(null, "Set ORIENTATION to LANDSCAPE and MARGINS to 1.0, 0.0, 1.0, 0.0", "WARNING!!!", JOptionPane.YES_NO_OPTION);

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String headerField = "Printed on " + sdf.format(new Date());

        MessageFormat header = new MessageFormat(headerField);
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");

        if (warningPopup == JOptionPane.YES_OPTION) {

            try {

                CarTable.print(JTable.PrintMode.NORMAL, header, footer);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_PrintButtonMouseClicked

    private void PriceTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PriceTextBoxKeyPressed
        // TODO add your handling code here:
        //Key Pressed Validation for numbers only

        char numbers = evt.getKeyChar();

        if (Character.isLetter(numbers)) {

            PriceTextBox.setEditable(false);//only numbers in text field

            //PriceWarningLabel.setText("Please Enter ONLY number in this text field!");
        } else {
            PriceTextBox.setEditable(true);
        }
    }//GEN-LAST:event_PriceTextBoxKeyPressed

    private void YearTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_YearTextBoxKeyPressed
        // TODO add your handling code here:
        //Key Pressed Validation for numbers only

        char numbers = evt.getKeyChar();

        if (Character.isLetter(numbers)) {

            YearTextBox.setEditable(false);//only numbers in text field

            //YearWarningLabel.setText("Please Enter ONLY number in this text field!");
        } else {
            YearTextBox.setEditable(true);
        }
    }//GEN-LAST:event_YearTextBoxKeyPressed

    private void QuantityTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_QuantityTextBoxKeyPressed
        // TODO add your handling code here:
        //Key Pressed Validation for numbers only

        char numbers = evt.getKeyChar();

        if (Character.isLetter(numbers)) {

            QuantityTextBox.setEditable(false);//only numbers in text field

            //QuantityTextBox.setText("Please Enter ONLY number in this text field!");
        } else {
            QuantityTextBox.setEditable(true);
        }
    }//GEN-LAST:event_QuantityTextBoxKeyPressed

    private void MileageTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MileageTextBoxKeyPressed
        // TODO add your handling code here:
        //Key Pressed Validation for numbers only

        char numbers = evt.getKeyChar();

        if (Character.isLetter(numbers)) {

            MileageTextBox.setEditable(false);//only numbers in text field

            //MileageTextBox.setText("Please Enter ONLY number in this text field!");
        } else {
            MileageTextBox.setEditable(true);
        }
    }//GEN-LAST:event_MileageTextBoxKeyPressed

    private void PowerTextBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PowerTextBoxKeyPressed
        // TODO add your handling code here:
        char numbers = evt.getKeyChar();

        if (Character.isLetter(numbers)) {

            PowerTextBox.setEditable(false);//only numbers in text field

            //PriceWarningLabel.setText("Please Enter ONLY number in this text field!");
        } else {
            PowerTextBox.setEditable(true);
        }
    }//GEN-LAST:event_PowerTextBoxKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToyotaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToyotaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToyotaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToyotaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToyotaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JTable CarTable;
    private javax.swing.JTextField ColourTextBox;
    private javax.swing.JTextField ConditionTextBox;
    private javax.swing.JLabel CustomersLabel;
    private javax.swing.JComboBox<String> DriveTypeComboBox;
    private javax.swing.JTextField FuelTypeTextBox;
    private javax.swing.JLabel LogOutLabel;
    private javax.swing.JTextField MakeTextBox;
    private javax.swing.JTextField MileageTextBox;
    private javax.swing.JTextField ModelTextBox;
    private javax.swing.JLabel OrdersLabel;
    private javax.swing.JTextField PowerTextBox;
    private javax.swing.JTextField PriceTextBox;
    private javax.swing.JLabel PriceWarningLabel;
    private javax.swing.JButton PrintButton;
    private javax.swing.JButton ProductRemoveButton;
    private javax.swing.JButton ProductUpdateButton;
    private javax.swing.JButton ProductsAddButton;
    private javax.swing.JLabel ProductsFormExitLabel;
    private javax.swing.JLabel ProductsLabel;
    private javax.swing.JTextField QuantityTextBox;
    private javax.swing.JLabel StockLabel;
    private javax.swing.JTextField YearTextBox;
    private javax.swing.JLabel YearWarningLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
